package ugrep

// Generated by https://quicktype.io

type Data struct {
	File    string  `json:"file"`
	Matches []Match `json:"matches"`
}

type Match struct {
	Line   int64  `json:"line"`
	Column int64  `json:"column"`
	Match  string `json:"match"`
}
