// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"gitee.com/xuender/gca"
	"github.com/xuender/ag-ui/ag"
	"github.com/xuender/ag-ui/pb"
)

// Injectors from wire.go:

func InitApp() *gca.App[*pb.Msg] {
	service := ag.NewService()
	app := NewApp(service)
	return app
}
