// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/xuender/agp/ag"
	"github.com/xuender/agp/pb"
	"github.com/xuender/gca"
)

// Injectors from wire.go:

func InitApp() *gca.App[*pb.Msg] {
	config := pb.NewConfig()
	service := ag.NewService(config)
	app := NewApp(service)
	return app
}
