// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/xuender/gca"
	"github.com/xuender/grephub/pb"
	"github.com/xuender/grephub/search"
	"github.com/xuender/grephub/search/ag"
	"github.com/xuender/grephub/search/rg"
	"github.com/xuender/kit/oss"
)

// Injectors from wire.go:

func InitApp() *gca.App[*pb.Msg] {
	config := pb.NewConfig()
	procInfo := oss.NewProcInfo()
	agAg := ag.NewAg()
	rgRg := rg.NewRg()
	service := search.NewService(config, procInfo, agAg, rgRg)
	app := NewApp(service)
	return app
}
