// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirs() {
  return window['go']['app']['App']['AddDirs']();
}

export function Config() {
  return window['go']['app']['App']['Config']();
}

export function DelDir(arg1) {
  return window['go']['app']['App']['DelDir'](arg1);
}

export function Open(arg1) {
  return window['go']['app']['App']['Open'](arg1);
}

export function Query(arg1) {
  return window['go']['app']['App']['Query'](arg1);
}
