// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pb} from '../models';

export function AddDirs():Promise<void>;

export function Config():Promise<pb.Msg>;

export function DelDir(arg1:string):Promise<void>;

export function Open(arg1:string):Promise<void>;

export function Query(arg1:pb.Query):Promise<pb.Query>;
