// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['app']['Service']['About']();
}

export function AddDirs() {
  return window['go']['app']['Service']['AddDirs']();
}

export function AsyncQuery(arg1) {
  return window['go']['app']['Service']['AsyncQuery'](arg1);
}

export function Config() {
  return window['go']['app']['Service']['Config']();
}

export function DelDir(arg1) {
  return window['go']['app']['Service']['DelDir'](arg1);
}

export function Open(arg1) {
  return window['go']['app']['Service']['Open'](arg1);
}

export function Query(arg1) {
  return window['go']['app']['Service']['Query'](arg1);
}
