### get
POST http://localhost:8080/api/ag
Content-Type: application/json

{"pattern":"book","path":"/home/ender/work/23/ag-ui"}
### get2
POST http://localhost:8080/api/ag
Content-Type: application/json

{"pattern":"a"}