// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_config Type = 0
	Type_query  Type = 1
	Type_ack    Type = 2
	Type_open   Type = 3
	Type_select Type = 4
	Type_stop   Type = 5
	Type_alert  Type = 6
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "config",
		1: "query",
		2: "ack",
		3: "open",
		4: "select",
		5: "stop",
		6: "alert",
	}
	Type_value = map[string]int32{
		"config": 0,
		"query":  1,
		"ack":    2,
		"open":   3,
		"select": 4,
		"stop":   5,
		"alert":  6,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_msg_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_pb_msg_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_pb_msg_proto_rawDescGZIP(), []int{0}
}

// Msg 消息.
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   Type     `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Type" json:"type,omitempty"`
	Query  *Query   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Ack    *Ack     `protobuf:"bytes,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Open   string   `protobuf:"bytes,4,opt,name=open,proto3" json:"open,omitempty"`
	Select string   `protobuf:"bytes,5,opt,name=select,proto3" json:"select,omitempty"`
	Dirs   []string `protobuf:"bytes,6,rep,name=dirs,proto3" json:"dirs,omitempty"`
	Alert  string   `protobuf:"bytes,7,opt,name=alert,proto3" json:"alert,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_pb_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_config
}

func (x *Msg) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Msg) GetAck() *Ack {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *Msg) GetOpen() string {
	if x != nil {
		return x.Open
	}
	return ""
}

func (x *Msg) GetSelect() string {
	if x != nil {
		return x.Select
	}
	return ""
}

func (x *Msg) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *Msg) GetAlert() string {
	if x != nil {
		return x.Alert
	}
	return ""
}

var File_pb_msg_proto protoreflect.FileDescriptor

var file_pb_msg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0e, 0x70, 0x62, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb5, 0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x19, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x03, 0x61,
	0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x69, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x69,
	0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2a, 0x51, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x73, 0x74, 0x6f, 0x70, 0x10, 0x05,
	0x12, 0x09, 0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x10, 0x06, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_proto_rawDescOnce sync.Once
	file_pb_msg_proto_rawDescData = file_pb_msg_proto_rawDesc
)

func file_pb_msg_proto_rawDescGZIP() []byte {
	file_pb_msg_proto_rawDescOnce.Do(func() {
		file_pb_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_proto_rawDescData)
	})
	return file_pb_msg_proto_rawDescData
}

var file_pb_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_msg_proto_goTypes = []interface{}{
	(Type)(0),     // 0: pb.Type
	(*Msg)(nil),   // 1: pb.Msg
	(*Query)(nil), // 2: pb.Query
	(*Ack)(nil),   // 3: pb.Ack
}
var file_pb_msg_proto_depIdxs = []int32{
	0, // 0: pb.Msg.type:type_name -> pb.Type
	2, // 1: pb.Msg.query:type_name -> pb.Query
	3, // 2: pb.Msg.ack:type_name -> pb.Ack
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_msg_proto_init() }
func file_pb_msg_proto_init() {
	if File_pb_msg_proto != nil {
		return
	}
	file_pb_query_proto_init()
	file_pb_ack_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_msg_proto_goTypes,
		DependencyIndexes: file_pb_msg_proto_depIdxs,
		EnumInfos:         file_pb_msg_proto_enumTypes,
		MessageInfos:      file_pb_msg_proto_msgTypes,
	}.Build()
	File_pb_msg_proto = out.File
	file_pb_msg_proto_rawDesc = nil
	file_pb_msg_proto_goTypes = nil
	file_pb_msg_proto_depIdxs = nil
}
