// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Msg 消息.
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *Query `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Acks  []*Ack `protobuf:"bytes,2,rep,name=acks,proto3" json:"acks,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_pb_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Msg) GetAcks() []*Ack {
	if x != nil {
		return x.Acks
	}
	return nil
}

var File_pb_msg_proto protoreflect.FileDescriptor

var file_pb_msg_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x0e, 0x70, 0x62, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0c, 0x70, 0x62, 0x2f, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x43, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x04, 0x61, 0x63, 0x6b, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x6b, 0x52,
	0x04, 0x61, 0x63, 0x6b, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_proto_rawDescOnce sync.Once
	file_pb_msg_proto_rawDescData = file_pb_msg_proto_rawDesc
)

func file_pb_msg_proto_rawDescGZIP() []byte {
	file_pb_msg_proto_rawDescOnce.Do(func() {
		file_pb_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_proto_rawDescData)
	})
	return file_pb_msg_proto_rawDescData
}

var file_pb_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_msg_proto_goTypes = []interface{}{
	(*Msg)(nil),   // 0: pb.Msg
	(*Query)(nil), // 1: pb.Query
	(*Ack)(nil),   // 2: pb.Ack
}
var file_pb_msg_proto_depIdxs = []int32{
	1, // 0: pb.Msg.query:type_name -> pb.Query
	2, // 1: pb.Msg.acks:type_name -> pb.Ack
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_msg_proto_init() }
func file_pb_msg_proto_init() {
	if File_pb_msg_proto != nil {
		return
	}
	file_pb_query_proto_init()
	file_pb_ack_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_msg_proto_goTypes,
		DependencyIndexes: file_pb_msg_proto_depIdxs,
		MessageInfos:      file_pb_msg_proto_msgTypes,
	}.Build()
	File_pb_msg_proto = out.File
	file_pb_msg_proto_rawDesc = nil
	file_pb_msg_proto_goTypes = nil
	file_pb_msg_proto_depIdxs = nil
}
